### PR TITLE
Fixed broken links in `_index.md`

### PR DESCRIPTION
**Pull request by michaella23**
## Type of Contribution

Check the item(s) that applies.

- [ ] :zap: HOWTO Content update
- [ ] 📃 Hugo static site update
- [x] :icecream: README or site documentation update

### Is this pull request related to an existing issue? If so, which one is it?

- [ ] :white_check_mark: Yes! - Issue number:
- [x] :x: No, sorry.

## Description

I noticed that the links for HOWTO - Contributors and HOWTO - Maintainers were getting a 404 response, so I changed the URL in the markdown and they seem to redirect correctly now.

### CODE REVIEW

**Comment by zo0o0ot** [comment]
If possible, could you tell me more about broken links the issue you ran into?

Trying out the site in Chrome, I didn't run into any 404 errors.
howto-links

However, if there is an issue, I'd like to try to resolve it.  Hopefully, we can continue using relative links, just in case I ever decide to add a domain name, or if GitHub pages stops using the io domain.

**Comment by michaella23** [comment]
Sure. I am using Mac OS and Chrome Browser. I was in the `_index.md` file and clicked on the links there. I had expected it to take me to the corresponding Markdown files in GitHub, but maybe I misunderstood how the routing is working.

**Comment by zo0o0ot** [comment]
No problem. You're right that this entire project started off as a bunch of markdown files.  
The old version is here:
https://github.com/zo0o0ot/hacktoberfest-issue-howto

This new version is stored as markdown files, but Hugo parses it into a static site that is hosted on GitHub Pages at https://hacktoberfesthowto.github.io/

**Comment by michaella23** [comment]
I see! Thanks for the info! I don't quite know what to contribute to this repo I guess. It's cool though! Some nice resources. 🙂

**Comment by zo0o0ot** [comment]
I would love help with #33 if you have time. I see that you made a comment there.

**Comment by zo0o0ot** [comment]
I've assigned you to #33 but because of the good quality conversation on this PR, I'm marking this also as a Hacktoberfest approved PR.

**Pull request closed without merging**
